apiVersion: kubevirt.io/v1alpha1
kind: VM
metadata:
  name: testvm-fedora
spec:
  domain:
    devices:
      graphics:
      - type: spice
      interfaces:
      - type: network
        source:
          network: default
      video:
      - type: qxl
      disks:
      - type: network
        snapshot: external
        device: disk
        driver:
          name: qemu
          type: qcow2
          cache: none
        source:
          host:
            name: iscsi-demo-target.default
            port: "3260"
          protocol: iscsi
          name: iqn.2017-01.io.kubevirt:sn.42/4
        target:
          dev: vda
      consoles:
      - type: pty
    memory:
      unit: MB
      value: 256
    os:
      type:
        os: hvm
    type: qemu
